### ISSUE TITLE
won't patch app manifests, and won't work unless i open and close

### ISSUE THREAD

**Issue by owoguy** [vendetta-mod/VendettaManager#13]
![Screenshot_20230531-141427_Vendetta Manager](https://github.com/vendetta-mod/VendettaManager/assets/86011827/3478f35d-e3b7-4efa-b9c3-f2b16112db7e)
VendettaManager v1.0.82
Built from commit 2771865 on main (Changes Present)

Running Android 10, API level 29
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi

Checking if base-178019.apk is cached
base-178019.apk is cached
Move base-178019.apk to working directory
Checking if config.arm64_v8a-178019.apk is cached
config.arm64_v8a-178019.apk is cached
Move config.arm64_v8a-178019.apk to working directory
Checking if config.en-178019.apk is cached
config.en-178019.apk is cached
Move config.en-178019.apk to working directory
Checking if config.xxhdpi-178019.apk is cached
config.xxhdpi-178019.apk is cached
Move config.xxhdpi-178019.apk to working directory
Checking if vendetta.apk is cached
vendetta.apk is cached
Move vendetta.apk to working directory
Reading AndroidManifest.xml from base-178019.apk

Failed on step PATCH_MANIFESTS

java.lang.RuntimeException: Failed to open archive: InvalidArchive("Invalid zip header")
	at com.github.diamondminer88.zip.ZipReader.open(Native Method)
	at com.github.diamondminer88.zip.ZipReader.<init>(ZipReader.java:39)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.install(InstallerViewModel.kt:299)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.access$install(InstallerViewModel.kt:40)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel$job$1$1.invokeSuspend(InstallerViewModel.kt:106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by wingio** [comment]
That error means that an apk was corrupted, usually clearing the cache fixes it

**Comment by owoguy** [comment]
i tried multiple times to clear the cache
but im gunna try reinstalling the installer apk

**Comment by wingio** [comment]
Just to follow up, did reinstalling end up working?

**Comment by owoguy** [comment]
yes
