### ISSUE TITLE
Double click about crash

### ISSUE THREAD

**Issue by Mikicrepstudios** [vendetta-mod/VendettaManager#18]
When you click fast 2 times on about button, app will just crash

**Comment by searinminecraft** [comment]
can confirm this

https://github.com/vendetta-mod/VendettaManager/assets/114207889/b747d449-c9bd-4259-889c-faf3ea2a4dd8

**Comment by Wojtaz0w** [comment]
Still an issue... 
```
FATAL EXCEPTION: main
Process: dev.beefers.vendetta.manager, PID: 16693
java.lang.IllegalArgumentException: Key dev.beefers.vendetta.manager.ui.screen.about.AboutScreen:transition was used multiple times 
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:89)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:88)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1091)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:818)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:839)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:592)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1241)
	at android.view.Choreographer.doCallbacks(Choreographer.java:901)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1216)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7933)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:843)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@972dc0b, androidx.compose.ui.platform.MotionDurationScaleImpl@753ae8, StandaloneCoroutine{Cancelling}@14cf501, AndroidUiDispatcher@30cfa6]
```

**Comment by searinminecraft** [comment]
Now it seems to crash if clicking on an icon button that triggers an transition 2 times (back buttons dont seem to be affected though, it just glitches the screen)

**Comment by Wojtaz0w** [comment]
For me it still does very much crash the app. 
```
FATAL EXCEPTION: main
Process: dev.beefers.vendetta.manager, PID: 8388
java.lang.IllegalArgumentException: Key dev.beefers.vendetta.manager.ui.screen.settings.SettingsScreen:transition was used multiple times
	at coil.size.ViewSizeResolver$size$3$1.invoke(SourceFile:534)
	at coil.size.ViewSizeResolver$size$3$1.invoke(SourceFile:80)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Unknown Source:4)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Unknown Source:106)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Unknown Source:61)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Unknown Source:5)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Unknown Source:171)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1341)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:878)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@381c134, androidx.compose.ui.platform.MotionDurationScaleImpl@9554b5d, StandaloneCoroutine{Cancelling}@d359cd2, AndroidUiDispatcher@207f1a3]
```
