### ISSUE TITLE
failed to sign apk

### ISSUE THREAD

**Issue by soccerboys2008** [vendetta-mod/VendettaManager#19]
but it worked fine after I hit the install button again, so it doesn't seem reproducible, but I still snagged a log as a jic

Device: Oneplus 6t (Lineage OS 20, 20-20230302-NIGHTLY-fajita)

Here's the log from when it failed:
```
Vendetta Manager v1.0.85
Built from commit 3e4ad68 on main (Changes Present)

Running Android 13, API level 33
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi

Checking if base-186011.apk is cached
base-186011.apk is cached
Move base-186011.apk to working directory
Checking if config.arm64_v8a-186011.apk is cached
config.arm64_v8a-186011.apk is not cached, downloading now
Move config.arm64_v8a-186011.apk to working directory
Checking if config.en-186011.apk is cached
config.en-186011.apk is cached
Move config.en-186011.apk to working directory
Checking if config.xxhdpi-186011.apk is cached
config.xxhdpi-186011.apk is cached
Move config.xxhdpi-186011.apk to working directory
Checking if vendetta.apk is cached
vendetta.apk is not cached, downloading now
Move vendetta.apk to working directory
Replacing mipmap-xhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xhdpi-v4 with ic_logo_square.png
Replacing mipmap-xxhdpi-v4 with ic_logo_square.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_square.png
Replacing mipmap-xhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_foreground.png
Reading AndroidManifest.xml from base-186011.apk
Changing package and app name in base-186011.apk
Deleting old AndroidManifest.xml in base-186011.apk
Adding patched AndroidManifest.xml in base-186011.apk
Reading AndroidManifest.xml from config.arm64_v8a-186011.apk
Changing package and app name in config.arm64_v8a-186011.apk
Changing package name in config.arm64_v8a-186011.apk
Deleting old AndroidManifest.xml in config.arm64_v8a-186011.apk
Adding patched AndroidManifest.xml in config.arm64_v8a-186011.apk
Reading AndroidManifest.xml from config.en-186011.apk
Changing package and app name in config.en-186011.apk
Changing package name in config.en-186011.apk
Deleting old AndroidManifest.xml in config.en-186011.apk
Adding patched AndroidManifest.xml in config.en-186011.apk
Reading AndroidManifest.xml from config.xxhdpi-186011.apk
Changing package and app name in config.xxhdpi-186011.apk
Changing package name in config.xxhdpi-186011.apk
Deleting old AndroidManifest.xml in config.xxhdpi-186011.apk
Adding patched AndroidManifest.xml in config.xxhdpi-186011.apk
Creating dir for signed apks
Byte aligning base-186011.apk
Removing old resources.arsc
Adding aligned resources.arsc
Byte aligning config.arm64_v8a-186011.apk
Byte aligning config.en-186011.apk
Removing old resources.arsc
Adding aligned resources.arsc
Byte aligning config.xxhdpi-186011.apk
Removing old resources.arsc
Adding aligned resources.arsc
Signing base-186011.apk

Failed on step SIGN_APK

com.android.apksig.apk.MinSdkVersionException: Failed to determine APK's minimum supported Android platform version
	at com.android.apksig.ApkSigner.getMinSdkVersionFromApk(ApkSigner.java:905)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:268)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:204)
	at dev.beefers.vendetta.manager.installer.util.Signer.signApk(Signer.kt:116)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.install(InstallerViewModel.kt:355)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.access$install(InstallerViewModel.kt:40)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel$install$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.android.apksig.zip.ZipFormatException: CRC-32 mismatch between Local File Header and Central Directory for entry AndroidManifest.xml. LFH: 3383847149, CD: 3422663616
	at com.android.apksig.internal.zip.LocalFileRecord.getRecord(LocalFileRecord.java:191)
	at com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:427)
	at com.android.apksig.internal.zip.LocalFileRecord.getUncompressedData(LocalFileRecord.java:451)
	at com.android.apksig.ApkSigner.getAndroidManifestFromApk(ApkSigner.java:865)
	at com.android.apksig.ApkSigner.getMinSdkVersionFromApk(ApkSigner.java:903)
	... 14 more
```

**Comment by wingio** [comment]
I've never even seen that error before, my guess is it somehow got corrupted but idk
