### ISSUE TITLE
Unable to download base APK

### ISSUE THREAD

**Issue by leap0x7b** [vendetta-mod/VendettaManager#2]
![Screenshot_20230327-141203_Vendetta_Manager.png](https://user-images.githubusercontent.com/76893443/227867187-852167a3-abc7-4781-af44-dc9e0051568d.png)

Logs:
```
Vendetta Manager 1.0.6
Built from commit f6855e6 on main (Changes Present)

Running Android 13, API level 33
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi

Checking if base-172205.apk is cached
base-172205.apk is not cached, downloading now

Failed on step DL_BASE_APK

java.lang.Error: Failed to download https://aliucord.com//download/discord?v=172205 because of: HTTP Data Error
	at dev.beefers.vendetta.manager.domain.manager.DownloadManager$download$2$receiver$1.onReceive(DownloadManager.kt:85)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7914)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```

**Comment by leap0x7b** [comment]
My internet is fine
