### ISSUE TITLE
keeps failing at random points in installation,

### ISSUE THREAD

**Issue by jameslandon786** [vendetta-mod/VendettaManager#20]
sometimes itll fail while downloading the base APKs, or it'll fail while injecting, just any random spots. I keep clearing the cache and retrying.

**Comment by jameslandon786** [comment]
Btw, I'm using a Samsung device, if that helps.

**Comment by riichimaru** [comment]
> Btw, I'm using a Samsung device, if that helps.

it won't help, you can send logs maybe??

**Comment by jameslandon786** [comment]
> > Btw, I'm using a Samsung device, if that helps.
> 
> it won't help, you can send logs maybe??

I can't find any logs.

**Comment by jameslandon786** [comment]
Wait never mind, here you go:
Vendetta Manager v1.0.85
Built from commit 3e4ad68 on main (Changes Present)

Running Android 13, API level 33
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi

Checking if base-186011.apk is cached
base-186011.apk is not cached, downloading now
Move base-186011.apk to working directory
Checking if config.arm64_v8a-186011.apk is cached
config.arm64_v8a-186011.apk is not cached, downloading now
Move config.arm64_v8a-186011.apk to working directory

Failed on step DL_LIBS_APK

kotlin.io.NoSuchFileException: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/186011/config.arm64_v8a-186011.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.install(InstallerViewModel.kt:194)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.access$install(InstallerViewModel.kt:40)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel$install$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

This is just an example of a random fail.

**Comment by AkhilTehSpartan** [comment]
Yeah it's getting failed download pls fix that we want to install
