### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by zleepyzeezee** [vendetta-mod/VendettaManager#43]
I've never written a report like this, so please pardon my lack of experience.

I was attempting to install Vendetta with the latest manager, and everything completes up until the Installation stage.

It would simply fail.
I thought it was a simple mistake on my part, forgetting to allow third-party app installation, but even with it allowed it would still consistently fail.

Here is the install log:

```
Vendetta Manager v1.0.98
Built from commit d6929c1 on main (Changes Present)

Running Android 12, API level 31
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi

Checking if base-206016.apk is cached
base-206016.apk is cached
Move base-206016.apk to working directory
Checking if config.arm64_v8a-206016.apk is cached
config.arm64_v8a-206016.apk is cached
Move config.arm64_v8a-206016.apk to working directory
Checking if config.en-206016.apk is cached
config.en-206016.apk is cached
Move config.en-206016.apk to working directory
Checking if config.xxhdpi-206016.apk is cached
config.xxhdpi-206016.apk is cached
Move config.xxhdpi-206016.apk to working directory
Checking if vendetta.apk is cached
vendetta.apk is cached
Move vendetta.apk to working directory
Replacing mipmap-xhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xhdpi-v4 with ic_logo_square.png
Replacing mipmap-xxhdpi-v4 with ic_logo_square.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_square.png
Replacing mipmap-xhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_foreground.png
Reading AndroidManifest.xml from base-206016.apk
Changing package and app name in base-206016.apk
Deleting old AndroidManifest.xml in base-206016.apk
Adding patched AndroidManifest.xml in base-206016.apk
Reading AndroidManifest.xml from config.arm64_v8a-206016.apk
Changing package and app name in config.arm64_v8a-206016.apk
Changing package name in config.arm64_v8a-206016.apk
Deleting old AndroidManifest.xml in config.arm64_v8a-206016.apk
Adding patched AndroidManifest.xml in config.arm64_v8a-206016.apk
Reading AndroidManifest.xml from config.en-206016.apk
Changing package and app name in config.en-206016.apk
Changing package name in config.en-206016.apk
Deleting old AndroidManifest.xml in config.en-206016.apk
Adding patched AndroidManifest.xml in config.en-206016.apk
Reading AndroidManifest.xml from config.xxhdpi-206016.apk
Changing package and app name in config.xxhdpi-206016.apk
Changing package name in config.xxhdpi-206016.apk
Deleting old AndroidManifest.xml in config.xxhdpi-206016.apk
Adding patched AndroidManifest.xml in config.xxhdpi-206016.apk
Creating dir for signed apks
Byte aligning base-206016.apk
Removing old resources.arsc
Adding aligned resources.arsc
Byte aligning config.arm64_v8a-206016.apk
Byte aligning config.en-206016.apk
Removing old resources.arsc
Adding aligned resources.arsc
Byte aligning config.xxhdpi-206016.apk
Removing old resources.arsc
Adding aligned resources.arsc
Signing base-206016.apk
Signing config.arm64_v8a-206016.apk
Signing config.en-206016.apk
Signing config.xxhdpi-206016.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/signed/base-206016.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/patched/lspatched/base-206016-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/signed/base-206016.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: androidx.core.app.CoreComponentFactory
original minSdkVersion: 24
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/patched/lspatched/base-206016-375-lspatched.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/signed/config.arm64_v8a-206016.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/patched/lspatched/config.arm64_v8a-206016-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/signed/config.arm64_v8a-206016.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: null
original minSdkVersion: 0
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/patched/lspatched/config.arm64_v8a-206016-375-lspatched.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/signed/config.en-206016.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/patched/lspatched/config.en-206016-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/signed/config.en-206016.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: null
original minSdkVersion: 0
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/patched/lspatched/config.en-206016-375-lspatched.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/signed/config.xxhdpi-206016.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/patched/lspatched/config.xxhdpi-206016-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/signed/config.xxhdpi-206016.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: null
original minSdkVersion: 0
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/206016/patched/lspatched/config.xxhdpi-206016-375-lspatched.apk
Gathering final apks
Installing apks

Failed on step INSTALL_APK

java.io.IOException: Failed to allocate 72191342 because only 0 allocatable
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
	at android.os.Parcel.readParcelable(Parcel.java:3346)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
	at android.os.Parcel.createException(Parcel.java:2422)
	at android.os.Parcel.readException(Parcel.java:2405)
	at android.os.Parcel.readException(Parcel.java:2347)
	at android.content.pm.IPackageInstallerSession$Stub$Proxy.openWrite(IPackageInstallerSession.java:595)
	at android.content.pm.PackageInstaller$Session.openWrite(PackageInstaller.java:1043)
	at dev.beefers.vendetta.manager.installer.util.PackageInstallerKt.installApks(PackageInstaller.kt:29)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.install(InstallerViewModel.kt:412)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.access$install(InstallerViewModel.kt:42)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel$job$1$1.invokeSuspend(InstallerViewModel.kt:123)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at com.android.server.pm.PackageInstallerSession.openWrite(PackageInstallerSession.java:1557)
	at android.content.pm.IPackageInstallerSession$Stub.onTransact(IPackageInstallerSession.java:277)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)
```

Thanks for reading and considering! :3c
-Izzy

**Comment by rushiiMachine** [comment]
Ran out of device space most likely

**Comment by zleepyzeezee** [comment]
Yep, I should have checked my storage capacity. 
Sorry for bothering!
