### ISSUE TITLE
Fail at downloading apks

### ISSUE THREAD

**Issue by YounesSamatta** [vendetta-mod/VendettaManager#85]
![Screenshot_20240321_155717_Vendetta Manager](https://github.com/vendetta-mod/VendettaManager/assets/96547485/ab330a4e-5596-42f3-b0ca-c9029aeed47c)

`here are the logs:`

03-21-2024 3:55:35PM [I] Vendetta Manager v1.1.23
03-21-2024 3:55:35PM [I] Built from commit 5e35d97 on main (Changes Present)
03-21-2024 3:55:35PM [I] 
03-21-2024 3:55:35PM [I] Running Android 14, API level 34
03-21-2024 3:55:35PM [I] Supported ABIs: armeabi-v7a, armeabi
03-21-2024 3:55:35PM [I] Device: samsung - SM-A135F (a13)
03-21-2024 3:55:35PM [I] SOC: Samsung Exynos 850
03-21-2024 3:55:35PM [I] 
03-21-2024 3:55:35PM [I] Adding Vendetta to Discord v221.16 - Stable
03-21-2024 3:55:35PM [I] 
03-21-2024 3:55:35PM [I] 
03-21-2024 3:55:35PM [I] Checking if base-221016.apk is cached
03-21-2024 3:55:35PM [I] base-221016.apk was not properly cached, downloading now
03-21-2024 3:55:37PM [D] base-221016.apk download progress: 0%
03-21-2024 3:55:38PM [D] base-221016.apk download progress: 0%
03-21-2024 3:55:40PM [D] base-221016.apk download progress: 4%
03-21-2024 3:55:42PM [D] base-221016.apk download progress: 9%
03-21-2024 3:55:44PM [D] base-221016.apk download progress: 13%
03-21-2024 3:55:44PM [D] base-221016.apk download progress: 14%
03-21-2024 3:55:46PM [D] base-221016.apk download progress: 18%
03-21-2024 3:55:48PM [D] base-221016.apk download progress: 22%
03-21-2024 3:55:50PM [D] base-221016.apk download progress: 26%
03-21-2024 3:55:52PM [D] base-221016.apk download progress: 29%
03-21-2024 3:55:54PM [D] base-221016.apk download progress: 33%
03-21-2024 3:55:56PM [D] base-221016.apk download progress: 36%
03-21-2024 3:55:58PM [D] base-221016.apk download progress: 41%
03-21-2024 3:56:00PM [D] base-221016.apk download progress: 45%
03-21-2024 3:56:02PM [D] base-221016.apk download progress: 47%
03-21-2024 3:56:03PM [D] base-221016.apk download progress: 48%
03-21-2024 3:56:04PM [D] base-221016.apk download progress: 50%
03-21-2024 3:56:06PM [D] base-221016.apk download progress: 53%
03-21-2024 3:56:08PM [D] base-221016.apk download progress: 56%
03-21-2024 3:56:10PM [D] base-221016.apk download progress: 59%
03-21-2024 3:56:12PM [D] base-221016.apk download progress: 62%
03-21-2024 3:56:14PM [D] base-221016.apk download progress: 65%
03-21-2024 3:56:17PM [D] base-221016.apk download progress: 68%
03-21-2024 3:56:19PM [D] base-221016.apk download progress: 71%
03-21-2024 3:56:21PM [D] base-221016.apk download progress: 73%
03-21-2024 3:56:23PM [D] base-221016.apk download progress: 74%
03-21-2024 3:56:26PM [D] base-221016.apk download progress: 75%
03-21-2024 3:56:28PM [D] base-221016.apk download progress: 75%
03-21-2024 3:56:30PM [D] base-221016.apk download progress: 76%
03-21-2024 3:56:32PM [D] base-221016.apk download progress: 77%
03-21-2024 3:56:35PM [D] base-221016.apk download progress: 77%
03-21-2024 3:56:37PM [D] base-221016.apk download progress: 78%
03-21-2024 3:56:39PM [D] base-221016.apk download progress: 78%
03-21-2024 3:56:42PM [D] base-221016.apk download progress: 79%
03-21-2024 3:56:44PM [D] base-221016.apk download progress: 81%
03-21-2024 3:56:46PM [D] base-221016.apk download progress: 83%
03-21-2024 3:56:48PM [D] base-221016.apk download progress: 84%
03-21-2024 3:56:50PM [D] base-221016.apk download progress: 86%
03-21-2024 3:56:52PM [D] base-221016.apk download progress: 89%
03-21-2024 3:56:54PM [D] base-221016.apk download progress: 94%
03-21-2024 3:56:56PM [D] base-221016.apk download progress: 98%
03-21-2024 3:56:58PM [I] Verifying downloaded file
03-21-2024 3:56:58PM [I] 
03-21-2024 3:56:58PM [I] 
03-21-2024 3:56:58PM [E] Failed on DownloadBaseStep
03-21-2024 3:56:58PM [E] java.lang.IllegalStateException: Downloaded file is missing: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/221016/base-221016.apk
03-21-2024 3:56:58PM [E] 	at dev.beefers.vendetta.manager.installer.step.download.base.DownloadStep.verify(Unknown Source:85)
03-21-2024 3:56:58PM [E] 	at dev.beefers.vendetta.manager.installer.step.download.base.DownloadStep.run$suspendImpl(Unknown Source:358)
03-21-2024 3:56:58PM [E] 	at dev.beefers.vendetta.manager.installer.step.download.base.DownloadStep$run$1.invokeSuspend(Unknown Source:12)
03-21-2024 3:56:58PM [E] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
03-21-2024 3:56:58PM [E] 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:112)
03-21-2024 3:56:58PM [E] 	at androidx.work.Worker$2.run(Unknown Source:12)
03-21-2024 3:56:58PM [E] 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
03-21-2024 3:56:58PM [E] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)

**Comment by YounesSamatta** [comment]
I managed to fix it, the problem occurs when you don't have enough storage space left
So make sure you have atleast 2-3gb free before installing.
