### ISSUE TITLE
Discord app crashes when opening discord

### ISSUE THREAD

**Issue by Miko0187** [vendetta-mod/VendettaManager#89]
![Screenshot_2024-04-03-12-07-36-928_dev.beefers.vendetta.jpg](https://github.com/vendetta-mod/VendettaManager/assets/113242324/ec0c969b-0e3c-4f11-b3e7-aef07a491aa0)

```
RangeError: Maximum call stack size exceeded (native stack depth)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    ... skipping 188 frames
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at call (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:721:151)
    at toString (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:716:937)
    at call (native)
    at _isNativeFunction (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:90:103)
    at _wrapNativeSuper (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:89:187)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:4573:969)
    at loadModuleImplementation (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1246)
    at guardedLoadModule (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1524)
    at metroRequire (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1530)
    at metroImportDefault (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1655)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:4572:628)
    at loadModuleImplementation (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1246)
    at guardedLoadModule (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1524)
    at metroRequire (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1530)
    at metroImportDefault (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1655)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:4571:109)
    at loadModuleImplementation (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1246)
    at guardedLoadModule (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1524)
    at metroRequire (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:2:1530)
    at anonymous (Vendetta:1:1307)
    at l (Vendetta:1:2149)
    at anonymous (Vendetta:1:15540)
    at anonymous (Vendetta:1:74)
    at anonymous (Vendetta:1:18715)
    at anonymous (Vendetta:1:74)
    at anonymous (Vendetta:5:24124)
    at anonymous (Vendetta:1:74)
    at anonymous (Vendetta:5:24288)
    at tryCallOne (/tmp/tmp2noz02z5/ReactAndroid/hermes-engine/.cxx/MinSizeRel/e385u6c7/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/tmp/tmp2noz02z5/ReactAndroid/hermes-engine/.cxx/MinSizeRel/e385u6c7/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:107:2002)
    at _callTimer (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:107:539)
    at _callReactNativeMicrotasksPass (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:107:981)
    at callReactNativeMicrotasks (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:107:3805)
    at __callReactNativeMicrotasks (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:45:3259)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:45:1096)
    at __guard (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:45:2846)
    at flushedQueue (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:45:1054)
```

**Comment by VoIcanis** [comment]
In case you haven't figured it out yet, some people were mean to the creator (I think threatened but not entirely sure) and they discontinued support of the app.. you van enable developer mode, roll forward to a working version and then disable checks for updates
